Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  DefaultContextTimeout: 60
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:8000/static
  UploadImageMaxSize: 10  # MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
Database:
  DBType: mysql
  Username: root   # 填写你的数据库账号
  Password: 123456  # 填写你的数据库密码
  Host: 127.0.0.1:3306
  DBName: goose
  TablePrefix: goose_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
RedisPool:
  MaxIdle: 16           # 最初的连接数量
  #  MaxActive: 10000      # 最大连接数量
  MaxActive: 0          # 连接池最大连接数量,不确定可以用0（0表示自动定义），按需分配
  IdleTimeout: 300      # 连接关闭时间 300秒 （300秒不使用自动关闭）
  Host: 127.0.0.1:6379  # Redis连接
  Protocol: tcp         # 协议类型
JWT:
  Secret: Hanmur
  Issuer: goose-service
  Expire: 7200
Email:
  Host: smtp.qq.com
  Port: 465
  UserName: 未注册
  Password: 未注册
  IsSSL: true
  From: 1466046208@qq.com
  To:
    - 1466046208@qq.com
